name: Run unit tests
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8, 3.9, 3.10 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tools
        run: python -m pip install coverage requests

      - name: Wait for grocy to be available
        run: python3 tests/http_wait.py

      - name: Run tests
        run: coverage run -m unittest

      - name: Convert coverage
        run: coverage xml

      - name: Upload coverage
        uses: codecov/codecov-action@v2
